name: CI/CD for Next.js with json-server

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Start json-server
        run: npm run server &
        env:
          PORT: 3001 

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Application
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN
